### Задание на повторение материала

In [1]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [41]:
a = np.array(range(12, 24))
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [43]:
ss = [(1,12), (2, 6), (3, 4), (4, 3), (6, 2)]
for s in ss:
    print(np.reshape(a, s), '\n')

[[12 13 14 15 16 17 18 19 20 21 22 23]] 

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]] 



3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [44]:
a1 = np.reshape(a, (-1, 3))
a1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [45]:
a2 = np.reshape(a, (-1, 6))
a2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [46]:
a3 = np.reshape(a, (4, -1))
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [47]:
a4 = np.reshape(a, (12, -1))
a4

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [48]:
a5 = np.reshape(a, (1, -1))
a5

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [50]:
a5.shape == a.shape

False

In [51]:
np.array_equal(a, a5)

False

Судя по всему нет

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [54]:
a = np.array(range(20, 0, -2))
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [55]:
b = np.array([range(20, 1, -2)])
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [57]:
a.shape

(10,)

In [58]:
b.shape

(1, 10)

У массивов разные shape, массив a - одномерный, в отличие от b

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [69]:
a = np.array(range(12))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
A = np.reshape(a, (4, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [71]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [73]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Размер матрицы B

In [74]:
B.size

16

In [82]:
B_inv = np.linalg.inv(B)
B_inv

LinAlgError: Singular matrix

In [83]:
np.linalg.det(B)

0.0

Получаем ошибку LinAlgError: Singular matrix. 
Мы получили B - квадратную матрицу, определитель которой равен 0, поэтому обратную матрицу от B получить не удается.

10. Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [136]:
np.random.seed(42)
np.random.randint(10)

6

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [186]:
c = np.array([np.random.randint(0, 16) for _ in range(16)])
c

array([ 9,  9, 15,  4,  6,  3,  0, 13, 13,  4,  6,  9,  9,  5,  4,  3])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [187]:
C = np.reshape(c, (4, -1))
C

array([[ 9,  9, 15,  4],
       [ 6,  3,  0, 13],
       [13,  4,  6,  9],
       [ 9,  5,  4,  3]])

In [188]:
C = C * 10
C

array([[ 90,  90, 150,  40],
       [ 60,  30,   0, 130],
       [130,  40,  60,  90],
       [ 90,  50,  40,  30]])

In [189]:
D = B + C
D

array([[ 95, 104, 173,  72],
       [ 74,  80,  86, 252],
       [153, 126, 209, 302],
       [122, 172, 252, 332]])

In [190]:
_det = np.linalg.det(D)
_det # определитель матрицы D

-50259599.99999993

In [193]:
_rank = np.linalg.matrix_rank(D)
_rank # ранг матрицы

4

In [192]:
D_inv = np.linalg.inv(D)
D_inv # обратная матрица

array([[ 0.0144259 ,  0.01489865,  0.00686197, -0.02067903],
       [ 0.03171056,  0.04201267, -0.03312322, -0.00863596],
       [-0.0177765 , -0.03230587,  0.01469331,  0.01501086],
       [-0.00823644, -0.00271908,  0.0034859 ,  0.00369124]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [199]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [203]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [204]:
C

array([[ 90,  90, 150,  40],
       [ 60,  30,   0, 130],
       [130,  40,  60,  90],
       [ 90,  50,  40,  30]])

In [205]:
E = np.where(D_inv > 0, B, C)
E

array([[  5,  14,  23,  40],
       [ 14,  50,   0, 130],
       [130,  40, 149, 212],
       [ 90,  50, 212, 302]])