## Задание 4
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 3 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [1]:
import numpy as np

In [2]:
a = np.load('a.npy')
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
a_transposed = np.transpose(a)
a_transposed

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [4]:
result = np.cov(a_transposed)
result

array([[1. , 2. ],
       [2. , 4.3]])

In [5]:
covariance = result[0, 1]
covariance

2.0

ковариация, полученная в задании 3

In [6]:
naive_covariance = np.load('naive_covariance.npy')
naive_covariance

array(2.)

In [7]:
naive_covariance == covariance

True